"""
This type stub file was generated by pyright.
"""

inf = ...
eps = ...
def mt(game, gamma, depth, origDepth, scoring, tt=...): # -> int:
    """
    This implements Memory-Enhanced Test with transposition tables.
    This method is not meant to be used directly.
    This implementation is inspired by paper:
    http://arxiv.org/ftp/arxiv/papers/1404/1404.1515.pdf
    """
    ...

def mtd(game, first, next, depth, scoring, tt=...): # -> int:
    """
    This implements Memory-Enhanced Test Driver.
    This method is not meant to be used directly.
    It's used by several algorithms from MT family, i.e see ``easyAI.SSS``
    For more details read following paper:
    http://arxiv.org/ftp/arxiv/papers/1404/1404.1515.pdf
    """
    ...

