"""
This type stub file was generated by pyright.
"""

class HashTranspositionTable:
    """
    Base Class for various types of hashes
    """
    def __init__(self) -> None:
        ...
    
    def before(self, key): # -> Literal[0]:
        """
        Returns initial value of hash.
        It's also the place where you can initialize some auxiliary variables
        """
        ...
    
    def after(self, key, hash):
        """
        Returns final value of hash
        """
        ...
    
    def get_hash(self, key, depth=...): # -> int:
        """
        Recursively computes a hash
        """
        ...
    
    def hash_int(self, number):
        """
        Returns hash for a number
        """
        ...
    
    def hash_char(self, string): # -> int:
        """
        Returns hash for an one-letter string
        """
        ...
    
    def join(self, one, two):
        """
        Returns combined hash from two hashes
        one - existing (combined) hash so far
        two - hash of new element
        one = join(one, two)
        """
        ...
    


